import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.pdfbox.text.PDFTextStripperByArea;


public final class StatisticsUI extends javax.swing.JFrame {
    String OutputRuta;
    File file;
    String [][] tableValues;
    public StatisticsUI() {
        initComponents();
        tableValues = new String[48][3];
        this.setLocationRelativeTo(null);
    }
     public void PDFReader(){
        try (PDDocument document = PDDocument.load(file)) {
            document.getClass();
            if (!document.isEncrypted()){
                PDFTextStripperByArea stripper = new PDFTextStripperByArea();
                stripper.setSortByPosition(true);
                PDFTextStripper Tstripper = new PDFTextStripper();
                String str = Tstripper.getText(document);
                Scanner scn;
                scn = new Scanner(str);
                String line;
                while (scn.hasNextLine()) {
                    line = scn.nextLine();
                    System.out.println(line);
                    if(line.equalsIgnoreCase("Lectura Hora Voltaje (Volts)")){
                        fillMatrix(scn);
                        break;
                    }
                }
            }  
        }catch (IOException e) {
            System.err.print(e);
        }
    }
     public void fillMatrix(Scanner scn) throws FileNotFoundException, MalformedURLException {
        int matrixRows = 0;
        String line;

         float realVolts = 127.00F;

         List<Mensuration> mensList = new ArrayList<Mensuration>();
        while(scn.hasNextLine()){
            line = scn.nextLine();
            String[] divideEqual = line.split(" ");
            
            //
            //System.arraycopy(divideEqual, 0, this.tableValues[matrixRows], 0, 3);
            //System.out.println(divideEqual[0] + " - " + divideEqual[1] + " - " + divideEqual[2]);
            mensList.add(new Mensuration(Float.parseFloat(divideEqual[2]), Integer.parseInt(divideEqual[0]), divideEqual[0]));
            //
            
            matrixRows++;
        }

        for(Mensuration mensuration: mensList) {
            System.out.println(mensuration);
        }

         StaticMethods statical = new StaticMethods(mensList, realVolts);
         Graphics Graph = new Graphics();

         System.out.println("Arithmetic Average: " + statical.arithmeticAverage() + " volts");
         System.out.println("\nErrors: ");
         List<Error> absoluteErrors = statical.getErrors();
         for (Error error: absoluteErrors)
             System.out.println("Hour: " + error.hour + "\nAE: " + error.getAbsolute() + " volts" + "\nRE: " + error.getRelative() + "%");

         System.out.println("\nMedian: " + statical.median() + " volts");
         Graph.writeGraphics(statical.getFrequencies(),statical.getErrors(),this.OutputRuta);
         Frequency moreRepeated = statical.getMoreRepeated();
         System.out.println("More Repeated: " + moreRepeated.getEl() + " volts, Frequency: " + moreRepeated.getFrequency());


     }

     public static void createPDF ()
     {

     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        outputRoute = new javax.swing.JTextField();
        inputRoute = new javax.swing.JTextField();
        getRoutesButton = new javax.swing.JButton();
        convertToExcelButton = new javax.swing.JButton();
        inputLabelPath = new javax.swing.JLabel();
        outputLabelPath = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        pdfButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculador Estadistico ");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Tarea 1.2 Programa de calculos est�ditisticos");

        jLabel2.setFont(new java.awt.Font("MS Gothic", 2, 12)); // NOI18N
        jLabel2.setText("Instrumentaci�n Electr�nica: Equipo 1");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        outputRoute.setEditable(false);
        outputRoute.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        inputRoute.setEditable(false);
        inputRoute.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        getRoutesButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getRoutesButton.setText("Abrir");
        getRoutesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRoutesButtonActionPerformed(evt);
            }
        });

        convertToExcelButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        convertToExcelButton.setText("Seleccionar");
        convertToExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectOutputRouteActionPerformed(evt);
            }
        });

        inputLabelPath.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        inputLabelPath.setText("Archivo de entrada:");

        outputLabelPath.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        outputLabelPath.setText("Ruta de salida:");

        convertButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        convertButton.setText("Calcular");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        pdfButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pdfButton.setText("PDF CARNAL");
        pdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputRoute, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputRoute)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(inputLabelPath)
                                .addGap(0, 380, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getRoutesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(convertToExcelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(outputLabelPath)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(inputLabelPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getRoutesButton))
                .addGap(18, 18, 18)
                .addComponent(outputLabelPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertToExcelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents                        

    private void getRoutesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRoutesButtonActionPerformed
        JFileChooser inputRouteFile = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de pdf", "pdf");
        inputRouteFile.addChoosableFileFilter(filter);
        inputRouteFile.setAcceptAllFileFilterUsed(false);
        inputRouteFile.setMultiSelectionEnabled(false);
        inputRouteFile.showOpenDialog(this);
        
        this.file = inputRouteFile.getSelectedFile();
        if(this.file != null){
            inputRoute.setText(this.file.getAbsolutePath());
        }
        
    }//GEN-LAST:event_getRoutesButtonActionPerformed                                               
    private void selectOutputRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectOutputRouteActionPerformed
            JFileChooser chooser;
            chooser = new JFileChooser(); 
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Seleccionar ruta de salida");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);
        
            if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { 
                File outputFile = chooser.getSelectedFile();
                if(outputFile != null && outputFile.exists()){

                    outputRoute.setText(outputFile.getAbsolutePath());
                    this.OutputRuta = outputFile.getAbsolutePath();
                }
            }

    }//GEN-LAST:event_selectOutputRouteActionPerformed
    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(file == null){
            JOptionPane.showMessageDialog(null, "Primero selecciona un archivo de entrada", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            PDFReader();
            JOptionPane.showMessageDialog(null, "El programa ha concluido con exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException, MalformedURLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(StatisticsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            new StatisticsUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables                     
    private javax.swing.JButton convertButton;
    private javax.swing.JButton convertToExcelButton;
    private javax.swing.JButton getRoutesButton;
    private javax.swing.JLabel inputLabelPath;
    private javax.swing.JTextField inputRoute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel outputLabelPath;
    private javax.swing.JTextField outputRoute;
    private javax.swing.JButton pdfButton;
    // End of variables declaration//GEN-END:variables                   
   
}
